version: '3.8'
services:
  webserver:
    #image: httpd:latest
    build: ./apache/.
    ports:
      - 8080:80
    depends_on:
      - webapi
  webapi:
    build: .
    # ports:
    #   - 8989:80
  # volumes:
  #   - .:/var/www/html
